### ISSUE TITLE
Add Crowd Counting Consortium data on U.S. protest events since 2017?

### ISSUE THREAD

**Issue by nonviolent-action-lab** [erikgahner/PolData#12]
I work on the [Crowd Counting Consortium](https://sites.google.com/view/crowdcountingconsortium/home), and I think the compiled version of our dataset (on GitHub, [here](https://github.com/nonviolent-action-lab/crowd-counting-consortium)) would make a good addition to your list. It's comparable to the European protest datasets you list now, but it covers the U.S. since January 2017. It currently contains more than 110,000 records and is updated weekly.

In any case, thanks for creating and maintaining this resource.

**Comment by erikgahner** [comment]
Thank you so much! The dataset looks great and it is definitely a good addition to the overview. I have added it now.
